version: "3"
services:  
  jupiter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - /home/nikita/docker_test:/home/jovyan/
    ports:
        - 8888:8888
  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: example
volumes:
  pgdata: